### ISSUE TITLE
considered using Hibernate Panache as opposed to "classic" Entity and criteria building?

### ISSUE THREAD

**Issue by maxandersen** [diegocamara/realworld-api-quarkus#1]
browsing the code I noticed you are using "classic" Hibernate with Critieria API's - I think a lot of the entity pojos and the repository code can be greatly simplified using Hibernate Panache repository approach.

With that there would be no need to declare getter/setters on the entities and you get a good bunch of default/utility Repository methods available to you that should help reduce line count in services implementations.

Related question - why is the persistent model made separate from the model ? Is there a need for that somewhere ?

**Comment by diegocamara** [comment]
@maxandersen i used classic Hibernate Criteria API's just for personal taste, anyway i think migrate the persistence layer for entities can really simplify things. thanks for the suggestion.

About persistent package, plan to refactor later and remove it.

**Comment by maxandersen** [comment]
Cool :) tag me in a PR if you want feedback on it but otherwise awesome job to do this. nice to get some "realworld" examples out there!

**Comment by diegocamara** [comment]
Hibernate Panache implementation is ready.
