### ISSUE TITLE
Why does the codebase use a “feature” pattern?

### ISSUE THREAD

**Issue by franz-see** [diegocamara/realworld-api-quarkus#3]
Checking at the guides of Quarkus, it seems like it uses the typical java pattern of JAXRS API -> Service - Repository

This code base seem to use “Features” instead of “Services”. Any particular reason why?

**Comment by diegocamara** [comment]
Hi, in this code i chose to call "feature" small portions of business rules, trying to give these classes some unique responsibility but nothing prevents the creation of a "service" layer that works as a facade for these "features".
