### ISSUE TITLE
why the code is so complex???

### ISSUE THREAD

**Issue by KStephening** [diegocamara/realworld-api-quarkus#7]
api is very easy ,i do not understand why design this. can you give some explain ? thanks

**Comment by diegocamara** [comment]
Hi, i'm sorry for the late reply.
Well, I chose to create the features of this application in a less coupled way, following the SRP (single responsibility principle) and isolating the business logic in different classes.
I also considered that REST and persistence are infrastructure details.
REST endpoints are the primary ports for features.
Persistence (repository interfaces) are secondary ports and can be implemented by several adapters (in this case Panache modules).
Some architectural decisions actually make some applications more complex in exchange for some flexibility.
